### ISSUE TITLE
Can I use kinect(v1) run this program

### ISSUE THREAD

**Issue by wedwin** [YongYuH/Kinect-project#6]
Can I use kinect(v1) run this program?

**Comment by YuanRayChang** [comment]
NO

2016-09-23 16:31 GMT+08:00 wedwin notifications@github.com:

**Comment by YongYuH** [comment]
@wedwin 
This project uses Microsoft library Kinect SDK v2.0.
Kinect SDK v2.0 is designed for Kinect for Xbox One (v2).
It does not support Kinect for Xbox 360 (v1).
If you want to use library for Kinect v1, 
you should use Kinect SDK v1.8: http://www.microsoft.com/en-us/download/details.aspx?id=40278
You can refer to this article on stackoverflow:
http://stackoverflow.com/questions/27307750/kinect-for-windows-v1-with-sdk-2-0

**Comment by wedwin** [comment]
OK ,Thanks
